<a href="https://colab.research.google.com/github/hvhq/classificationp1/blob/master/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('gdrive')

Drive already mounted at gdrive; to attempt to forcibly remount, call drive.mount("gdrive", force_remount=True).


In [2]:
import pandas as pd
from google.colab import files
import sklearn
from sklearn import preprocessing
import numpy as np
import math
from sklearn.metrics import mean_squared_error

In [3]:
!pip install ipython-autotime
%load_ext autotime

In [4]:
files.upload()

Saving Fish.csv to Fish (1).csv


{'Fish.csv': b'\xef\xbb\xbfSpecies,Weight,Length1,Length2,Length3,Height,Width\r\nBream,242,23.2,25.4,30,11.52,4.02\r\nBream,290,24,26.3,31.2,12.48,4.3056\r\nBream,340,23.9,26.5,31.1,12.3778,4.6961\r\nBream,363,26.3,29,33.5,12.73,4.4555\r\nBream,430,26.5,29,34,12.444,5.134\r\nBream,450,26.8,29.7,34.7,13.6024,4.9274\r\nBream,500,26.8,29.7,34.5,14.1795,5.2785\r\nBream,390,27.6,30,35,12.67,4.69\r\nBream,450,27.6,30,35.1,14.0049,4.8438\r\nBream,500,28.5,30.7,36.2,14.2266,4.9594\r\nBream,475,28.4,31,36.2,14.2628,5.1042\r\nBream,500,28.7,31,36.2,14.3714,4.8146\r\nBream,500,29.1,31.5,36.4,13.7592,4.368\r\nBream,340,29.5,32,37.3,13.9129,5.0728\r\nBream,600,29.4,32,37.2,14.9544,5.1708\r\nBream,600,29.4,32,37.2,15.438,5.58\r\nBream,700,30.4,33,38.3,14.8604,5.2854\r\nBream,700,30.4,33,38.5,14.938,5.1975\r\nBream,610,30.9,33.5,38.6,15.633,5.1338\r\nBream,650,31,33.5,38.7,14.4738,5.7276\r\nBream,575,31.3,34,39.5,15.1285,5.5695\r\nBream,685,31.4,34,39.2,15.9936,5.3704\r\nBream,620,31.5,34.5,39.7,15.

time: 8.26 s


In [5]:
data=pd.read_csv("Fish.csv")
lendata=len(data)

#filter one species
#datab=pd.DataFrame(columns=['Species','Weight','Length1','Length2', 'Length3', 'Height', 'Width'])
#for i in range(0, lendata):
#  if data.Species[i]=='Bream':
#    datab=datab.append(data.iloc[i], ignore_index=True)
#data=datab
#lendata=len(data)

#encoder string to numeric
encoder=sklearn.preprocessing.LabelEncoder()
encoder.fit(data.Species)
data.Species=encoder.transform(data.Species)

#change domain to [0,1]
data.Length1=(data.Length1-([min(data.Length1)]*lendata))/([max(data.Length1)-min(data.Length1)]*lendata)
data.Length2=(data.Length2-([min(data.Length2)]*lendata))/([max(data.Length2)-min(data.Length2)]*lendata)
data.Length3=(data.Length3-([min(data.Length3)]*lendata))/([max(data.Length3)-min(data.Length3)]*lendata)
data.Height=(data.Height-([min(data.Height)]*lendata))/([max(data.Height)-min(data.Height)]*lendata)
data.Width=(data.Width-([min(data.Width)]*lendata))/([max(data.Width)-min(data.Width)]*lendata)
#data.Species=(data.Species-([min(data.Species)]*lendata))/([max(data.Species)-min(data.Species)]*lendata)
data.Weight=(data.Weight-([min(data.Weight)]*lendata))/([max(data.Weight)-min(data.Weight)]*lendata)

x=data.drop('Weight', axis=1)
y=pd.DataFrame(data.Weight)
trainOTestRate=3
xTrain=x
xTest=pd.DataFrame(columns=['Species', 'Length1', 'Length2', 'Length3', 'Height', 'Width'])
yTrain=y
yTest=pd.DataFrame(columns=['Weight'])
for i in range(0, len(data)):
  if i%(trainOTestRate+1)==0:
    xTest=xTest.append(x.iloc[i], ignore_index=True)
    xTrain=xTrain.drop([i])
    yTest=yTest.append(y.iloc[i], ignore_index=True)
    yTrain=yTrain.drop([i])
xTrain=xTrain.reset_index(drop=True)
yTrain=yTrain.reset_index(drop=True)

#xTrain=xTrain.to_numpy()
#xTest=xTest.to_numpy()
#yTrain=yTrain.to_numpy()
#yTest=yTest.to_numpy()
print("train")
print(xTrain)
print(yTrain)
print("test")
print(xTest)
print(yTest)


train
     Species   Length1   Length2   Length3    Height     Width
0          0  0.320388  0.325455  0.378378  0.624055  0.459235
1          0  0.318447  0.329091  0.376689  0.618123  0.514279
2          0  0.365049  0.374545  0.417230  0.638566  0.480365
3          0  0.374757  0.387273  0.437500  0.689203  0.546882
4          0  0.374757  0.387273  0.434122  0.722699  0.596372
..       ...       ...       ...       ...       ...       ...
114        5  0.075728  0.065455  0.074324  0.027628  0.014208
115        5  0.077670  0.069091  0.077703  0.021012  0.048771
116        5  0.081553  0.072727  0.079392  0.040723  0.031208
117        5  0.110680  0.107273  0.108108  0.066424  0.143719
118        5  0.122330  0.120000  0.125000  0.069872  0.117219

[119 rows x 6 columns]
       Weight
0    0.175758
1    0.206061
2    0.220000
3    0.272727
4    0.303030
..        ...
114  0.005939
115  0.007394
116  0.008121
117  0.011939
118  0.012061

[119 rows x 1 columns]
test
    Species   Len

In [6]:
yTrain=yTrain.iloc[:,0]
yTest=yTest.iloc[:,0]

lenTrain=len(xTrain)
numberInputAttr=6
vector0=np.array([0]*numberInputAttr)
xTrain=np.array(xTrain)

time: 2.97 ms


In [7]:
#batch gradient descent
#print(x)
#print(y)
theta=vector0*1

#train
alpha=0.001
numEpochs=100000
numLoops=0
iLoopGrade=1
while(numLoops<numEpochs):
  errors=np.dot(xTrain, np.transpose(theta))-yTrain
  sumerrors=np.dot(np.transpose(errors), xTrain)
  theta=theta-alpha*sumerrors
  #check convergent
  numLoops+=1
  if numLoops/iLoopGrade>1000:
    iLoopGrade*=1000
    alpha/=10

#result
print('theta: ',theta)

#test
test_results=np.dot(xTest, np.transpose(theta))
test_errors=np.dot(xTest, np.transpose(theta))-yTest
com_res=pd.DataFrame(test_results, columns=['cal_result'])
com_res.insert(1, 'check', yTest, True)
com_res.insert(2, 'error', test_errors, True)
#print(com_res)
print('Evaluate:')
mse=1.0/len(yTest)*np.sum([i*i for i in com_res.error])
mae=1.0/len(yTest)*np.sum([i if i>=0 else -i for i in com_res.error])
print('1-sqrt(mse):', 1-math.sqrt(mse))
print('1-mae:', 1-mae)


theta:  [-0.02484979  0.30305032  0.293232    0.06635236 -0.05090675  0.18655022]
Evaluate:
1-sqrt(mse): 0.9059384721563744
1-mae: 0.9225774971156803
time: 24.8 s


In [8]:
#stochatic gradient descent
theta=vector0*1
lenTrain=len(xTrain)
alpha=0.001
numEpochs=1000000
numLoops=0
iLoopGrade=1
while numLoops<numEpochs:
  error=np.dot(xTrain[numLoops%lenTrain], np.transpose(theta))-yTrain[numLoops%lenTrain]
  total_errors=np.dot(np.transpose(error), xTrain[numLoops%lenTrain])
  theta=theta-alpha*total_errors
  numLoops+=1


#result
print(theta)

#test
test_results=np.dot(xTest, np.transpose(theta))
test_errors=np.dot(xTest, np.transpose(theta))-yTest
com_res=pd.DataFrame(test_results, columns=['cal_result'])
com_res.insert(1, 'check', yTest, True)
com_res.insert(2, 'error', test_errors, True)
#print(com_res)
print('Evaluate:')
mse=1.0/len(yTest)*np.sum([i*i for i in com_res.error])
mae=1.0/len(yTest)*np.sum([i if i>=0 else -i for i in com_res.error])
print('1-sqrt(mse):', 1-math.sqrt(mse))
print('1-mae:', 1-mae)

[-0.02557028  0.30328286  0.29058423  0.09665792 -0.0723274   0.19182304]
Evaluate:
1-sqrt(mse): 0.9065461313434864
1-mae: 0.922501221593957
time: 14.4 s


In [9]:
#mini-batch gradient descent
theta=vector0*1
lenTrain=len(xTrain)
alpha=0.001
numEpochs=100
iLoops=0
numBatch=5
sizeBatch=lenTrain/numBatch+(lenTrain%numBatch!=0)
iBatch=0
iLoopGrade=1
while iLoops<numEpochs:
  #error=np.dot(xTrain[iBatch*sizeBatch:min((iBatch+1)*sizeBatch, lenTrain)], np.transpose(theta))-yTrain[iBatch*sizeBatch:min((iBatch+1)*sizeBatch, lenTrain)]
  #total_errors=np.dot(np.transpose(error), xTrain[iBatch*sizeBatch:min((iBatch+1)*sizeBatch, lenTrain)])
  #theta=theta-alpha*total_errors
  iBatch+=1
  if iBatch>=numBatch:
    iBatch=0
  iLoops+=1


#result
print(theta)

#test
test_results=np.dot(xTest, np.transpose(theta))
test_errors=np.dot(xTest, np.transpose(theta))-yTest
com_res=pd.DataFrame(test_results, columns=['cal_result'])
com_res.insert(1, 'check', yTest, True)
com_res.insert(2, 'error', test_errors, True)
#print(com_res)
print('Evaluate:')
mse=1.0/len(yTest)*np.sum([i*i for i in com_res.error])
mae=1.0/len(yTest)*np.sum([i if i>=0 else -i for i in com_res.error])
print('1-sqrt(mse):', 1-math.sqrt(mse))
print('1-mae:', 1-mae)

[0 0 0 0 0 0]
Evaluate:
1-sqrt(mse): 0.6626713848749479
1-mae: 0.7509136363636364
time: 21.3 ms


In [10]:
#formula
inverse_matrix=np.linalg.inv(np.dot(np.transpose(xTrain),xTrain))
theta=np.dot(np.dot(inverse_matrix,np.transpose(xTrain)), yTrain)
print(theta)

#test
test_results=np.dot(xTest, np.transpose(theta))
test_errors=np.dot(xTest, np.transpose(theta))-yTest
com_res=pd.DataFrame(test_results, columns=['cal_result'])
com_res.insert(1, 'check', yTest, True)
com_res.insert(2, 'error', test_errors, True)
#print(com_res)
print('Evaluate:')
mse=1.0/len(yTest)*np.sum([i*i for i in com_res.error])
mae=1.0/len(yTest)*np.sum([i if i>=0 else -i for i in com_res.error])
print('1-sqrt(mse):', 1-math.sqrt(mse))
print('1-mae:', 1-mae)

[-0.02037279  0.31165614  1.99397467 -1.64676851  0.19298268  0.00682802]
Evaluate:
1-sqrt(mse): 0.9047214055543749
1-mae: 0.9229798985796567
time: 21.5 ms
